#!/Users/nicolldavis/pdf_converter/bin/python3.11
import sys
from marker.scripts.convert_single import convert_single_cli
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(convert_single_cli())
