#!/Users/nicolldavis/pdf_converter/bin/python3.11
import sys
from marker.scripts.chunk_convert import chunk_convert_cli
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(chunk_convert_cli())
